package com.nickimpact.GTS.storage.rework.flatfile;

import com.nickimpact.GTS.GTS;
import com.nickimpact.GTS.storage.rework.Storage;

import java.io.File;

/**
 * This class represents the main structure to all files generated by the GTS plugin.
 * With the two sets of info in mind, we will store the main GTS info into a file declared
 * as data.json, along with logs in a file named logs.json.
 *
 * @author NickImpact
 */
public class FlatFileProvider implements Storage
{
    private File data = new File(GTS.getInstance().getConfigDir().toFile(), "data.json");
    private File logs = new File(GTS.getInstance().getConfigDir().toFile(), "logs.json");

    @Override
    public void init() throws Exception
    {

    }

    @Override
    public void shutdown() throws Exception
    {

    }

    @Override
    public void getLots()
    {

    }

    @Override
    public void getLogs()
    {

    }

    @Override
    public boolean purge(boolean logs)
    {
        return false;
    }

    @Override
    public boolean save()
    {
        return false;
    }
}
